global:
  scrape_interval: 1m # Define time between each scrapes

scrape_configs:
# Create prometheus datasource for prometheus
  - job_name: "prometheus"
    scrape_interval: 1m
    static_configs:
      - targets: ["localhost:9090"]

# Create haproxy-exporter datasource for prometheus
  - job_name: "haproxy-exporter"
    static_configs:
      - targets: ["haproxy_reporter:9101"]

# Allow to display Prometheus docker info on localhost:9090
remote_write:
  - url: "http://localhost:9090"
    basic_auth:
      username: "admin"
      password: "admin"
