apiVersion: 1

# Provide Prometheus datasource
datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      httpMethod: GET
      timeInterval: "5s"
      tlsSkipVerify: false
